apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin
spec:
  externalTrafficPolicy: Local
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 80
    protocol: TCP
  loadBalancerIP: 172.17.0.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: phpmyadmin
          protocol: TCP