apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: data
      port: 20
      targetPort: 20
      protocol: TCP
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-pasv 
      port: 30021
      targetPort: 30021
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-mypvc
  labels:
    app: ftps
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
          protocol: TCP
        - containerPort: 30021
          protocol: TCP
          name: ftps-data
        volumeMounts:
        - name: ftps-storage
          mountPath: /etc/ftps/admin
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: ftps-storage
        persistentVolumeClaim:
          claimName: ftps-mypvc
      restartPolicy: Always