apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - name: data
      port: 20
      targetPort: 20
      protocol: TCP
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-pasv 
      port: 30021
      targetPort: 30021
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
          protocol: TCP
        - containerPort: 30021
          protocol: TCP
          name: ftps-data
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always
