apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep php'
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always
