apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin
spec:
  externalTrafficPolicy: Local
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        resources:
        args:
          - sleep
          - infinity 
        ports:
        - containerPort: 5000
          name: phpmyadmin
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep php'
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always