apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - name: ftp
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftpst
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp
        - containerPort: 21
          name: ftps
