apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - port: 21000 
      targetPort: 21000
      protocol: TCP
      name: ftps-data
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
          protocol: TCP
        - containerPort: 21000
          protocol: TCP
          name: ftps-data
